[package]
name = "scijava"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0+"

[profile.release]
strip = true
opt-level = 3
lto = true
panic = "abort"
debug-assertions = false
overflow-checks = false
debug = false

[dependencies]
rug = "1.18.0"
jni = "0.20.0"

[lib]
crate-type = ["cdylib"]
