[package]
name = "scijava"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0+"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.18.0"
jni = "0.20.0"

[lib]
crate-type = ["cdylib"]
